mysiteS171/myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #  url(r'^base/$', views.base),
    url(r'^index/$', views.IndexView, name='index'),
    url(r'^home/$', views.HomeView, name='home'),
    url(r'^addan/$', views.AddAn, name='addan'),
    url(r'^addre/$', views.AddRe, name='addre'),
    url(r'^addprojects/$', views.AddProject, name='addproject'),
    url(r'^projects_list/$', views.Project_list),
    url(r'^addissues/$', views.AddIssues, name='addissues'),
    url(r'^issues_list/$', views.Issues_list),
    url(r'^profiles/$', views.Profiles),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^addmembers/$', views.AddMember, name='addmember'),
    url(r'^register/$', views.user_register, name='register'),
    # url(r'^index/$', views.index, name='index'),
    url(r'^(?P<issues_id>\d+)/$', views.Issues_Detail, name='issues_detail'),
    # url(r'^issues_detail/(?P<issues_id>\d+)/$', views.Issues_Detail,name='issues_detail'),
    # url(r'^topics/$', views.topics, name='topics'),

]

mysiteS171/mysiteS171/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/', include('myapp.urls', namespace='myapp')),
]

mysiteS171/myapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
# Create your models here.

class Announcement(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User)
    description = models.CharField(max_length=100000)
    date = models.DateField()
    def __str__(self):
        return self.title

class Member(models.Model):
    #members_no = models.IntegerField(max_length=5,primary_key=True)
    project_no = models.IntegerField()
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.CharField(max_length=50,null=True,blank=True)
    def __str__(self):
        return self.first_name + self.last_name

class Project(models.Model):
    project_no = models.IntegerField(primary_key=True)
    members = models.ManyToManyField(Member,blank=True)
    name = models.CharField(max_length=50)
    leader = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField()

    Communication = 0
    Planning = 1
    Modeling = 2
    Construction = 3
    Deployment = 4
    phase_choice = (
        (0, 'Communication'),
        (1, 'Planning'),
        (2, 'Modeling'),
        (3, 'Construction'),
        (4, 'Deploylment')
    )
    phase = models.IntegerField(default=0, choices=phase_choice)
    description = models.CharField(max_length=100000)

    def __str__(self):
        return str(self.project_no)+'  '+ self.name

class Requirement(models.Model):
    project = models.ForeignKey(Project)
    title = models.CharField(max_length=100)
    customer = models.CharField(max_length=100)
    description = models.CharField(max_length=100000)
    date = models.DateField()
    def __str__(self):
        return self.title

class Issue(models.Model):

    project = models.ForeignKey(Project)
    title = models.CharField(max_length=1000)
    description = models.CharField(max_length=100000)
    author = models.ForeignKey(User)
    date =  models.DateField()

    def __str__(self):
        return self.title


class Issue_Detail(models.Model):
    answer = models.CharField(max_length=100000)
    replyer = models.ForeignKey(User)
    issue = models.ForeignKey(Issue)

mysiteS171/myapp/forms.py
from django import forms

from .models import Announcement, Requirement, Project, Issue, Member, Issue_Detail, User


from django.contrib.auth.forms import UserCreationForm

class AnnouncementForm(forms.ModelForm):
    class Meta:
        model = Announcement
        fields = ['title', 'author', 'description']

  #  title = forms.CharField(label='Title', max_length=10000)
   # author = forms.CharField(label='Author', max_length=50)
   # description = forms.CharField(label='Description', widget=forms.Textarea)

class RequirementForm(forms.ModelForm):
    class Meta:
        model = Requirement
        fields = ['title', 'customer', 'project', 'description']
    #title = forms.CharField(label='Title', max_length=10000)
    #costumer = forms.CharField(label='Costumer', max_length=50)
    #description = forms.CharField(label='Description', widget=forms.Textarea)

class IssuesForm(forms.ModelForm):
    #object_name = forms.CharField(label='Object', widget=forms.Textarea)
    #description = forms.CharField(label='Description', widget=forms.Textarea)
    class Meta:
        model = Issue
        fields = ['project', 'title', 'description', 'author']

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['project_no','name','leader','start_date','end_date','phase','description']

class IssueDetailForm(forms.ModelForm):
    class Meta:
        model = Issue_Detail
        fields = ['answer']


class MembersForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['project_no', 'first_name', 'last_name', 'email']

#
# class MemberRegisterForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'first_name', 'last_name', 'email']
#
#         def _init_(self, *args, **kwargs):
#             super(UserCreationForm, self)._init_(*args, **kwargs)
#
#             self.fields['username'].widget.attrs['class'] = 'form-control'
#             self.fields['first_name'].widget.attrs['class'] = 'form-control'
#             self.fields['last_name'].widget.attrs['class'] = 'form-control'
#             self.fields['email'].widgets.attrs['class'] = 'form-control'

mysiteS171/myapp/views.py
from datetime import date
from django.contrib import messages
import re

from .models import Announcement, Requirement,  Project, Issue, Member, Issue_Detail
from .forms import ProjectForm, AnnouncementForm,RequirementForm,IssuesForm,MembersForm,IssueDetailForm
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView
from django.views import View
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Create your views here.
def base(request):
    return render(request, 'management/base1.html')

def HomeView(request):
    return render(request,'management/home.html')

def IndexView(request):
    try:
        acmt_list = Announcement.objects.all().order_by('-date')
        if request.user.username == 'mica':
            remt_list = Requirement.objects.all().order_by('-date')
            return render(request,'management/index.html',{'acmtlist': acmt_list, 'remtlist': remt_list})
        else:
            pro = Member.objects.get(email=request.user.email)
            remt_list = Requirement.objects.filter(project_id=pro.project_no).order_by('-date')
            return render(request,'management/index.html',{'acmtlist': acmt_list, 'remtlist': remt_list})
    except Member.DoesNotExist:
        acmt_list = Announcement.objects.all().order_by('-date')
        remt_list = None
        return render(request, 'management/index.html', {'acmtlist': acmt_list, 'remtlist': remt_list})

def AddAn(request):
    Aform = AnnouncementForm(request.POST)
    if request.method == 'POST':
        try:
            if Aform.is_valid():
                announcement = Aform.save(commit=False)
                announcement.date = date.today()
                announcement.save()
                messages.add_message(request, messages.SUCCESS, 'You have been submitted successfully!')
                Aform = AnnouncementForm()
        except:
            messages.add_message(request, messages.ERROR, 'Error! Please check your input again!')
            Aform = AnnouncementForm()
    else:
        Aform = AnnouncementForm()

    return render(request, 'management/addAn.html', {'Aform': Aform})

def AddRe(request):
    Rform = RequirementForm(request.POST)
    if request.method == 'POST':
        try:
            if Rform.is_valid():
                requirement = Rform.save(commit=False)
                requirement.date = date.today()
                requirement.save()
                messages.add_message(request, messages.SUCCESS, 'You have been submitted successfully!')
                Rform = RequirementForm()
        except:
            messages.add_message(request, messages.ERROR, 'Error! Please check your input again!')
            Rform = RequirementForm()
    else:
        Rform = RequirementForm()

    return render(request, 'management/addRe.html', {'Rform': Rform})

def AddProject(request):
    form = ProjectForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            project = form.save(commit=False)
            project.save()
            messages.add_message(request, messages.SUCCESS, 'You have been submitted successfully!')
            form = ProjectForm()
        else:
            messages.add_message(request, messages.ERROR, 'Error! Please check your input again!')
            form = ProjectForm()
    else:
        form = ProjectForm()

    return render(request, 'management/addprojects.html', {'form': form})

def Project_list(request):
    if Member.objects.filter(email=request.user.email).exists():
        member = Member.objects.filter(email=request.user.email)
        Project_list = Project.objects.filter(members=member)
    else:
        Project_list = Project.objects.all()
    return render(request, 'management/projects_list.html', {'Project_list': Project_list})

def AddIssues(request):
    if Member.objects.filter(email=request.user.email).exists() or request.user.username == 'mica':
        form = IssuesForm(request.POST)
        if request.method == 'POST':
            if form.is_valid():
                issue = form.save(commit=False)
                issue.date = date.today()
                issue.save()
                messages.add_message(request, messages.SUCCESS, 'You have been submitted successfully!')
                form = IssuesForm()
            else:
                messages.add_message(request, messages.ERROR, 'Error! Please check your input again!')
                form = IssuesForm()
        else:
            form = IssuesForm()
    else:
        messages.add_message(request, messages.ERROR, 'Please apply your project first!')
        form = None

    return render(request, 'management/addissues.html', {'form': form})


        #issue = Issue.objects.all()
    #answer = Issue.objects.values_list("object", flat=True)
    #form = IssuesForm(request.POST)
    #if form.is_valid():
    #    issue = form.save(commit=False)
    #    issue.save()

    #return render(request, 'management/addissues.html', {'issue':issue,'answer':answer})


def Issues_list(request):
    if request.user.username == 'mica':
        issue_list = Issue.objects.all()
    elif Member.objects.filter(email=request.user.email).exists():
        P_no = Member.objects.filter(email=request.user.email).values_list('project_no')
        issue_list = Issue.objects.filter(project=P_no)
    else:
        issue_list = None

    return render(request, 'management/issues_list.html', {'issue_list':issue_list})

def Issues_Detail(request,issues_id):
    issues = Issue.objects.get(id=issues_id)
    project = Project.objects.get(project_no=issues.project_id)
    author = User.objects.get(id=issues.author_id)

    answer = Issue_Detail.objects.filter(issue_id=issues_id)

    form = IssueDetailForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            issuedetail = form.save(commit=False)
            issuedetail.issue_id = issues_id
            issuedetail.replyer_id = request.user.id
            issuedetail.save()
            form = IssueDetailForm()
        else:
            form = IssueDetailForm()
    else:
        form = IssueDetailForm()

    return render(request, 'management/issues_detail.html',{'issues':issues, 'answer':answer, 'project':project, 'author':author, 'form':form})

def Profiles(request):
    try:
        if request.user.username == 'mica':
            Profiles = Member.objects.all()[:10]
        else:
            P_no = Member.objects.filter(email=request.user.email).values_list('project_no')
            Profiles = Member.objects.filter(project_no=P_no)
    except Member.DoesNotExist:
        Profiles = None
    #Profiles = Member.objects.all()[:10]
    #form = MembersForm(request.POST)
    #if form.is_valid():
    #    members = form.save(commit=False)
            #topic.num_responses = 1
    #    members.save()
            #return HttpResponseRedirect(reverse('management:'))

    return render(request, 'management/profiles.html',{'Profiles': Profiles})

def AddMember(request):
    form = MembersForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            member = form.save(commit=False)
            try:
                Project.objects.get(project_no=member.project_no)
                if Member.objects.filter(email=member.email, project_no=member.project_no).exists():
                    messages.add_message(request, messages.ERROR,
                                         'Error! The member already participates in this project!')
                    form = MembersForm()
                elif User.objects.filter(first_name=member.first_name, last_name=member.last_name, email=member.email).exists():
                    member.save()
                    messages.add_message(request, messages.SUCCESS, 'You have been submitted successfully!')
                    form = MembersForm()
                else:
                    messages.add_message(request, messages.ERROR, 'Error! We do not have this member!')
                    form = MembersForm()
            except Project.DoesNotExist:
                messages.add_message(request, messages.ERROR, 'Error! It seems project does not exist!')
                form = MembersForm()
        else:
            messages.add_message(request, messages.ERROR, 'Error! Please check your input again!')
            form = MembersForm()
    else:
        form = MembersForm()
    return render(request, 'management/addmembers.html', {'form':form})


#def topicdetail(request, topic_id):
#    topic = Topic.objects.filter(id=topic_id)
#    if request.method == 'POST':
#        form = InterestForm(request.POST)
#        if form.is_valid() and request.POST.get('interested') == '1':
#            interested = form.cleaned_data['interested']
#            age = form.cleaned_data['age']
#            for t in topic:
#                n = t.num_responses + 1
#                topic.update(num_responses=n)
#                a = (t.avg_age * t.num_responses + int(request.POST.get('age'))) / n
#                topic.update(avg_age=a)
#            return HttpResponseRedirect(reverse('myapp:topics'))
#        else:
#            return HttpResponseRedirect(reverse('myapp:topics'))
#    elif request.method == 'GET':
#        form = InterestForm()
#    return render(request, 'myapp/topicdetail.html', {'form': form, 'topic': topic})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('myapp:index'))
        else:

mysiteS171/myapp/templates/management/addAn.html
{% extends 'management/base1.html' %}

{% block body_block %}
    <head>
        <title>ADD ANNOUNCEMENT</title>
        <style>
            #addannreq {
                color: hotpink;
                font-size: large;
                font-weight: bolder;
                font-style: italic;
                font-family: Helvetica, Tahoma, Arial;
            }

        </style>
    </head>
    <!----------------Body Section Start---------------------->
    <section class="contact_page">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 m-t-50">
                    <h1 class="underline heading"><b>ANNOUNCEMENT POSTING</b></h1>
                </div>
            </div>

        </div>
    </section>
    <div class="container">
        <div class="container1">
            <div class="container2">
                <h1 align="center">ADD ANNOUNCEMENT</h1><br>
                <div style=" width: 400px; margin-left: 200px;">
                    <ul class="messages">
                        {% if messages %}
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                        {% endif %}
                    </ul>

                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ Aform.as_p }}
                        <input type="submit" value="submit" style="margin: 20px 120px"/>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!----------------Body Section End---------------------->
{% endblock %}

mysiteS171/myapp/templates/management/addRe.html
{% extends 'management/base1.html' %}

{% block body_block %}
    <head>
        <title>ADD REQUIREMENT</title>
        <style>
            #addannreq {
                color: hotpink;
                font-size: large;
                font-weight: bolder;
                font-style: italic;
                font-family: Helvetica, Tahoma, Arial;
            }

        </style>
    </head>
    <!----------------Body Section Start---------------------->
    <section class="contact_page">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 m-t-50">
                    <h1 class="underline heading"><b>REQUIREMENT POSTING</b></h1>
                </div>
            </div>

        </div>
    </section>
    <div class="container">
        <div class="container1">
            <div class="container2">
                <h1 align="center">ADD REQUIREMENT</h1><br>
                <div style=" width: 400px; margin-left: 200px;">
                    {% if messages %}
                        <ul class="messages" style="border: 1px solid yellow">
                            {% for message in messages %}
                                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ Rform.as_p }}
                        <input type="submit" value="submit" style="margin: 20px 120px"/>
                    </form>
                </div>
            </div>
        </div>

    </div>
 <!----------------Body Section End---------------------->
{% endblock %}

mysiteS171/myapp/templates/management/addannouncement.html
{% extends 'management/base.html' %}

{% block body_block %}

		<!----------------Body Section Start---------------------->
		<section class="contact_page">
			<div class="container">
				<div class="row">
					<div class="col-sm-6 col-sm-offset-3 m-t-50">
						<h1 class="underline heading">ANNOUNCEMENT POSTING</h1>
					</div>
				</div>

			</div>
		</section>
            <div class="container">
			    <div class="container1">
                    <div class="container2">
                        <h1 align="center">ANNOUNCEMENT</h1><br>
                            <form action="" method="POST">
                            {%  csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="submit"/>
                            </form>
                    </div>
			    </div>
			    <a href="#" id="return-to-top"><img src="../../static/myapp/images/backto.png" alt="image-missing"></a>
		    </div>
          <!----------------Body Section End---------------------->
{% endblock %}

mysiteS171/myapp/templates/management/addindex.html
{% extends 'management/base1.html' %}

{% block body_block %}
    <head>
        <title>ADD ANN & REQ</title>
        <style>
            #addannreq {
                color: hotpink;
                font-size: large;
                font-weight: bolder;
                font-style: italic;
                font-family: Helvetica, Tahoma, Arial;
            }

        </style>
    </head>
    <!----------------Body Section Start---------------------->
    <section class="contact_page">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 m-t-50">
                    <h1 class="underline heading"><b>ANNOUNCEMENT POSTING</b></h1>
                </div>
            </div>

        </div>
    </section>
    <div class="container">
        <div class="container1">
            <div class="container2">
                <h1 align="center">ANNOUNCEMENT</h1><br>
                <div style=" width: 400px; margin-left: 200px;">
                    <ul class="messages">
                        {% if messages %}
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                        {% endif %}
                    </ul>

                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ Aform.as_p }}
                        <input type="submit" value="submit" style="margin: 20px 120px"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="tp-header" id="tp-header"></div>
    <div class="container">
        <div class="container1">
            <div class="container2">
                <h1 align="center">REQUIREMENT</h1><br>
                <div style=" width: 400px; margin-left: 200px;">
                    {% if messages %}
                        <ul class="messages" style="border: 1px solid yellow">
                            {% for message in messages %}
                                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ Rform.as_p }}
                        <input type="submit" value="submit" style="margin: 20px 120px"/>
                    </form>
                </div>
            </div>
        </div>

    </div>
    <!----------------Body Section End---------------------->
{% endblock %}

mysiteS171/myapp/templates/management/addissues.html
{% extends 'management/base1.html' %}

{% block body_block %}
    <head>
        <title>ADD ISSUES</title>
        <style>
            #issues {
                color: hotpink;
                font-size: large;
                font-weight: bolder;
                font-style: italic;
                font-family: Helvetica, Tahoma, Arial;
            }
        </style>
    </head>
    <!----------------Body Section Start---------------------->

    <section class="contact_page">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 m-t-50">
                    <h1 class="underline heading"><b>SUBMIT ISSUES YOU ENCOUNTERED HERE</b></h1>
                </div>
            </div>

        </div>
    </section>
    <div class="container">
        <div class="container1">
            <div class="container2">
                <div style=" width: 400px; margin-left: 200px;">
                    <ul class="messages">
                        {% if messages %}
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}

                        {% endif %}
                    </ul>
                {% if form %}
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="submit" style="margin: 20px 120px"/>
                    </form>
                {% endif %}
                </div>
            </div>
        </div>
        <a href="#" id="return-to-top"><img src="../../static/myapp/images/backto.png" alt="image-missing"></a>
    </div>
    <!----------------Body Section End---------------------->
{% endblock %}

mysiteS171/myapp/templates/management/addprojects.html
{% extends 'management/base1.html' %}

{% block body_block %}
    <head>
        <title>CREATE PROJECTS</title>
        <style>
            #projects {
                color: hotpink;
                font-size: large;
                font-weight: bolder;
                font-style: italic;
                font-family: Helvetica, Tahoma, Arial;
            }
        </style>
    </head>
    <!----------------Body Section Start---------------------->
    <section class="contact_page">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 m-t-50">
                    <h1 class="underline heading"><b>CREATE A PROJECT HERE</b></h1>
                </div>
            </div>

        </div>
    </section>
    <div class="container">
        <div class="container1">
            <div class="container2">
                <div style=" width: 400px; margin-left: 200px;">
                    <ul class="messages">
                        {% if messages %}

                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}

                        {% endif %}
                    </ul>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="submit" style="margin: 20px 120px"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!----------------Body Section End---------------------->
{% endblock %}

mysiteS171/myapp/templates/management/home.html
{% extends 'management/base1.html' %}

{% block body_block %}
    <head>
        <meta charset="UTF-8">
        <title>HOME</title>
        <style>
            #home {
                color: hotpink;
                font-size: large;
                font-weight: bolder;
                font-style: italic;
                font-family: Helvetica, Tahoma, Arial;
            }
        </style>
    </head>
    <body>
    <!----------------Body Section Start---------------------->
    <section class="contact_page">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 m-t-50">
                    <h1 class="underline heading"><b>HOME</b></h1>

                </div>
            </div>

        </div>
    </section>
    <div class="container">
        <div class="container1"><img src="../../static/myapp/images/smoke.gif"style="margin-left: 60px"></div>
    </div>

    </body>
{% endblock %}

mysiteS171/myapp/templates/management/issues.html
{% extends 'management/base.html' %}

{% block body_block %}
		<!----------------Body Section Start---------------------->
		<section class="contact_page">
			<div class="container">
				<div class="row">
					<div class="col-sm-6 col-sm-offset-3 m-t-50">
						<h1 class="underline heading">Issues</h1>
					</div>
				</div>

			</div>
		</section>
		<div class="container">
			<div class="container1" id="object1">
				<dl>
					<dd>Object:</dd>
					<dt id="longdt">{{ issue.object }}</dt>
				</dl>
				<dl id="bigdl">
					<dd>Decsription:</dd>
					<dt id="bigdt">{{ issue.desrciption }}<br /></dt>
				</dl>
				<div class="dividediv"></div>
                {% for obj in solution %}
				<dl id="bigdl">{{ obj.answer }}</dl>
{#                <dl id="bigdl">{{ obj.replyer }}</dl>#}
{#				<dl id="bigdl">{{ obj.answer }}</dl>#}
                {% endfor %}
				<dl id="bigdl">
                    <form action="issues.html" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <input type="submit" value="OK">
                    </form>
{#					<dd> Add Solution:</dd>#}
{#					<textarea rows="8" cols="50"> </textarea>#}
				</dl>
{#				<button type="submit" form="#" value="Submit">Submit Solutions</button>#}
			</div>
			
			<a href="#" id="return-to-top"><img src="../../static/myapp/images/backto.png" alt="image-missing"></a>
		</div>

		<!----------------Body Section End---------------------->
{% endblock %}

mysiteS171/myapp/templates/management/issues_list.html
{% extends 'management/base1.html' %}

{% block body_block %}
    <head>
        <title>ISSUES LIST</title>
        <style>
            #issues {
                color: hotpink;
                font-size: large;
                font-weight: bolder;
                font-style: italic;
                font-family: Helvetica, Tahoma, Arial;
            }
        </style>
    </head>
    <!------------------Body Section Start----------------->
    <section class="contact_page">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 m-t-50">
                    <h1 class="underline heading"><b>ISSUE LIST</b></h1>
                </div>
            </div>

        </div>
    </section>
    <div class="container2">

        <table class="table table-hover">
        {% if issue_list %}
            <thead>
            <tr>
                <th>Issues Number</th>
                <th>Project Name</th>
                <th>Issues Name</th>
                <th>Time</th>
            </tr>
            </thead>
            {% for obj in issue_list %}
                <tbody class="tbody1">
                <tr class="">
                    <td><a href="{% url 'myapp:issues_detail' obj.id %}">{{ obj.id }}</a></td>
                    <td><a href="{% url 'myapp:issues_detail' obj.id %}">{{ obj.project }}</a></td>
                    <td><a href="{% url 'myapp:issues_detail' obj.id %}">{{ obj.title }}</a></td>
                    <td>{{ obj.date }}</td>
                </tr>
                </tbody>
            {% endfor %}
        {% else %}
            <br><div style="font-size: larger;text-align: center">There are no issues!</div>
        {% endif %}
        </table>
    </div>

{% endblock %}

mysiteS171/myapp/templates/management/logout.html
{% extends 'management/base1.html' %}

{% block body_block %}
    <h2>you can logout here!</h2>
{% endblock %}